import { SITE_NAME } from '@/config/conts';
import { Lock, FileCheck } from 'lucide-react';

export function ReportFooter() {
  const currentYear = new Date().getFullYear();

  return (
    <footer className="mt-24 pb-12 pt-8 border-t border-slate-200 dark:border-slate-800">
      <div className="flex flex-col items-center justify-center text-center gap-4">
        {/* Icona e Titolo di chiusura */}
        <div className="flex items-center gap-2 text-slate-400 font-semibold uppercase tracking-widest text-xs">
          <FileCheck className="w-4 h-4" />
          <span>End of Report</span>
        </div>

        {/* Disclaimer di Sicurezza */}
        <div className="max-w-2xl px-4">
          <p className="text-[10px] text-slate-400 leading-relaxed">
            This document contains confidential security information. The findings presented in this
            report reflect the security posture of the target system at the specific time of the
            scan. Vulnerabilities may have been remediated or new ones discovered since the
            generation date.
          </p>
        </div>

        {/* Branding & Copyright */}
        <div className="flex items-center gap-1.5 text-xs text-slate-300 font-medium mt-2">
          <Lock className="w-3 h-3" />
          <span>
            Generated by {SITE_NAME} &copy; {currentYear}
          </span>
        </div>
      </div>
    </footer>
  );
}
